# **Question 1   ** Create 2 lists with some brand names

In [10]:
Brand_List_1 = ['Apple','Google','Cisco','Microsoft','Tesla','Amazon','Facebook','Intel']
Brand_List_2 = ['Amazon','Google','Disney','Samsun','One-plus','Intel','Toyota','Cisco']

## Quetion 2 -List of overlapping brand names from both list

In [24]:
Brand_List_1
Brand_List_2
for i in Brand_List_1:
  for j in Brand_List_2:
    if i == j:
     print (i,end =",")

Google,Cisco,Amazon,Intel,

## Question 3-Print even numbers starting from 20 ending with 40

In [26]:
range(20,40,2)
for i in range(20,40,2):
  print (i,end = ",")

20,22,24,26,28,30,32,34,36,38,